#!/usr/bin/env python3

import http.server
import socketserver
from pathlib import Path
import os
PORT = 8000

Handler = http.server.SimpleHTTPRequestHandler

os.chdir(Path(__file__).absolute().parent)

if __name__ == "__main__":
    with socketserver.TCPServer(("", PORT), Handler) as httpd:
        print("serving at port", PORT)
        httpd.serve_forever()

        